#!/bin/bash

# Set terminfo dir (kitty sets it to its own dir, conflicts with tmux)
export TERMINFO='/usr/share/terminfo/'

# Load OS specific profile file
if [ -r "${HOME}/.bashrc" ]
then
  source "${HOME}/.bashrc"
fi
