#!/usr/bin/env bash

# Import functions
source "${HOME}/.dotfiles/share/bash/functions.sh"

# Source global definitions
source_file "/etc/bashrc"

# Get bash aliases from file if there is one
source_file "${HOME}/.bash_aliases"

# Source machine-specific configuration
source_file "${HOME}/.bashrc.local"

# Source OS-specific configuration
source_file "${HOME}/.bashrc.os"

# Define vim/vi as the default editor, if available
if [ -n "$(command -v vimx)" ]
then
  export EDITOR=vimx
elif [ -n "$(command -v vim)" ]
then
  export EDITOR=vim
elif [ -n "$(command -v vi)" ]
then
  export EDITOR=vi
fi

# Dictionaries path for hunspell
export DICPATH="${HOME}/.dictionaries"

source_file "${HOME}/.dotfiles/share/bash/prompt.sh"
