#!/bin/bash

# bash script for aliases

# Alias for vimx (on Fedora)
if [ -e /usr/bin/vimx ]
then
  alias vim="/usr/bin/vimx"
fi

# tmux minimal session for workspace
if [ -n "$(command -v tmux)" ] && [ -d "${HOME}/workspace" ]
then
  alias wks="tmux set-environment -g SYSTEM_THEME \"\$SYSTEM_THEME\" 2> /dev/null \
    ; tmux attach-session -x -f 'active-pane,ignore-size' -c ~/workspace -t workspace"
fi

# tmux rename window based on current working directory
_rename_tmux_window() {
  local -r window_name="$1"

  if [ -n "${TMUX}" ]; then
    if [ -n "${window_name}" ]
    then
      tmux rename-window "${window_name}"
      return
    fi

    local -r git_base_dir="$(git_base_directory)"

    if [ -n "${git_base_dir}" ]
    then
      tmux rename-window "${git_base_dir}"
    else
      tmux rename-window "$(basename "${PWD}")"
    fi
  fi
}

alias tname='_rename_tmux_window'

# Aliases for file editing
if [ -n "${EDITOR}" ]
then
  alias dotedit="cd \"\${HOME}/.dotfiles\" && \"\${EDITOR}\" ."

  if [ -z "$(command -v edit)" ]
  then
    alias edit="\"\${EDITOR}\""
  fi
fi

# Alias for listing local branches which no longer have their remote counterpart
alias ggone="git branch -vv | grep -i '\[.* gone\]' | awk '{ print \$1 }'"

# Alias for filtering modified/untracked git files in a branch
_filter_git_modified_untracked_files() {
  local filter=$1

  git status -su \
    | grep -E "^(\?\?|[MR ]M| D)" \
    | awk '{ print $2 }' \
    | grep -iE "${filter}"
}

alias gmu="_filter_git_modified_untracked_files"

# Securely remove (shred) files
if [ -n "$(command -v shred)" ]
then
  alias rrm="shred -zxuv -n10"
fi

# Local aliases
if [ -r "${HOME}/.bash_aliases.local" ]
then
  source "${HOME}/.bash_aliases.local"
fi
