#!/usr/bin/env bash

# Import functions
source "${HOME}/.dotfiles/share/bash/functions.sh"

# Source global definitions
source_file "/etc/bashrc"
source_file "/etc/bash.bashrc"

# Source OS-specific configuration
source_file "${HOME}/.bashrc.os"

# fzf keybindings (only on interactive shell sessions)
if [ -n "$(command -v fzf)" ] && [[ $- =~ i ]]
then
	# fzf keybindings for git
	source_file "${HOME}/.dotfiles/share/bash/fzf_git.sh"

	bind '"\er": redraw-current-line'
	bind '"\C-g\C-f": "$(_fzf_git_status)\e\C-e\er"'
	bind '"\C-g\C-b": "$(_fzf_git_branch)\e\C-e\er"'
	bind '"\C-g\C-h": "$(_fzf_git_log)\e\C-e\er"'
	bind '"\C-g\C-u": "$(_fzf_git_stash)\e\C-e\er"'
fi

# Get bash aliases from file if there is one
source_file "${HOME}/.bash_aliases"

# Source machine-specific configuration
source_file "${HOME}/.bashrc.local"

# Source git-prompt
source_file "$HOME/.git-prompt.sh"

source_file "$HOME/.dotfiles/share/bash/prompt.sh"
