#!/bin/bash

# bash script for aliases

# Alias for vimx (on Fedora)
if [ -e /usr/bin/vimx ]
then
  alias vim="/usr/bin/vimx"
fi

# tmux minimal session for workspace
if [ -n "$(command -v tmux)" ] && [ -d "${HOME}/workspace" ]
then
  alias workspace="tmux new-session -s workspace -n home -c \"\${HOME}/workspace\""
fi

# tmux rename window based on current working directory
_rename_tmux_window() {
  if [ -n "${TMUX}" ]; then
    if [ -n "$(git_base_directory)" ]
    then
      tmux rename-window "$(git_base_directory)"
    else
      tmux rename-window "$(basename "${PWD}")"
    fi
  fi
}

alias tname='_rename_tmux_window'

# Aliases for file editing
if [ -n "${EDITOR}" ]
then
  alias dotedit="cd \"\${HOME}/.dotfiles\" && \"\${EDITOR}\" ."

  if [ -z "$(command -v edit)" ]
  then
    alias edit="\"\${EDITOR}\""
  fi
fi

# Alias for listing local branches which no longer have their remote counterpart
alias ggone="git branch -vv | grep -i '\[.* gone\]' | awk '{ print \$1 }'"

# Alias for filtering modified/untracked git files in a branch
_filter_git_modified_untracked_files() {
  local filter=$1

  git status -su \
    | grep -E "^(\?\?|[MR ]M| D)" \
    | awk '{ print $2 }' \
    | grep -iE "${filter}"
}

alias gmu="_filter_git_modified_untracked_files"

# Local aliases
if [ -r "${HOME}/.bash_aliases.local" ]
then
  source "${HOME}/.bash_aliases.local"
fi
