#!/bin/bash

# Language settings
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Load OS specific profile file
if [ -r "${HOME}/.profile.os" ]
then
  source "${HOME}/.profile.os"
fi

# Add custom commands to path
if [ -d ~/opt/bin ]
then
  export PATH="$PATH:$HOME/opt/bin"
fi

# Load rbenv into PATH, if available
if [ -r "$HOME/.rbenv/bin" ]
then
  export PATH="$HOME/.rbenv/bin:$PATH"
fi

# Load rust/cargo tools into PATH, if available

if [ -r "${HOME}/.cargo/bin" ]
then
  export PATH="$HOME/.cargo/bin:$PATH"
fi
