#!/bin/bash

# Import functions
source "${HOME}/.dotfiles/share/bash/functions.sh"

# Language settings
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Dictionaries path for hunspell
export DICPATH="${HOME}/.dictionaries"

# Define vim/vi as the default editor, if available
if [ -n "$(command -v vimx)" ]
then
	export EDITOR=vimx
elif [ -n "$(command -v vim)" ]
then
	export EDITOR=vim
elif [ -n "$(command -v vi)" ]
then
	export EDITOR=vi
fi

# FZF settings
read -r -d '' FZF_CTRL_T_OPTS <<- EOM
--reverse
--bind ctrl-/:toggle-preview
--preview-window right:50%:border-left:hidden
--preview 'bat --color=always --style=grid,header {}'
EOM

export FZF_CTRL_T_COMMAND='fd --hidden --no-ignore --exclude ".git/" --type f'
export FZF_CTRL_T_OPTS="$FZF_CTRL_T_OPTS"
export FZF_TMUX_OPTS="-p 90%,90%"

# nvm settings (Node.js version manager)
export NVM_DIR="$HOME/.nvm"

# Load nvm and its bash completion
source_file "$NVM_DIR/nvm.sh"
source_file "$NVM_DIR/bash_completion"

# SDKMAN settings
export SDKMAN_DIR="$HOME/.sdkman"

# Init SDKMAN
source_file "$SDKMAN_DIR/bin/sdkman-init.sh"

# Go settings
export GOPATH="$HOME/go"

# List of paths to be loaded (in order of priority)
read -r -d '' PATHS_TO_LOAD <<- EOM
$HOME/opt/bin
$HOME/.rbenv/bin
$HOME/.cargo/bin
$GOPATH/bin
/usr/local/go/bin
EOM

# Initial PATH
MY_PATH="$HOME/bin:/usr/local/bin:/usr/bin:/bin"

# Load list of paths into PATH
for p in $PATHS_TO_LOAD
do
	[ -r "$p" ] && MY_PATH="$p:$MY_PATH"
done
export PATH="$MY_PATH"

# Load OS specific profile file
source_file "$HOME/.profile.os"
