#!/bin/bash

# Language settings
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Load OS specific profile file
if [ -r "$HOME/.profile.os" ]
then
  source "$HOME/.profile.os"
fi

# Initial PATH
MY_PATH="$HOME/bin:/usr/local/bin:/usr/bin:/bin"

# Add custom commands to path
if [ -r "$HOME/opt/bin" ]
then
  MY_PATH="$MY_PATH:$HOME/opt/bin"
fi

# Load rbenv into PATH, if available
if [ -r "$HOME/.rbenv/bin" ]
then
  MY_PATH="$HOME/.rbenv/bin:$MY_PATH"
fi

# Load rust/cargo tools into PATH, if available
if [ -r "$HOME/.cargo/bin" ]
then
  MY_PATH="$HOME/.cargo/bin:$MY_PATH"
fi

# Go settings
export GOPATH="$HOME/go"

# Load GOPATH/bin tools into PATH, if available
if [ -r "$GOPATH/bin" ]
then
  MY_PATH="$GOPATH/bin:$MY_PATH"
fi

# Load Go tools into PATH, if available
if [ -r "/usr/local/go/bin" ]
then
  MY_PATH="/usr/local/go/bin:$MY_PATH"
fi

export PATH="$MY_PATH"
