" Plugin manager
so ~/.vim/plugins.vim

" Row numbers
set number
set numberwidth=5
set relativenumber

" Text columns
set textwidth=80
set colorcolumn=+1

" Highlight cursor line
set cursorline

" Highlight and incremental search
if has("extra_search")
  set hlsearch
  set incsearch
endif

" Assures that Backspace deletes indent, eol and start
set backspace=indent,eol,start

" Extra whitespace
set list listchars=tab:»\ ,trail:·,nbsp:·

" Syntax
syntax on

" Theme
syntax enable
set background=dark
colorscheme solarized

" Clipboard
if has("clipboard")
  set clipboard=unnamed
  if has("unnamedplus")
    set clipboard+=unnamedplus
  endif
endif

set go+=a

" Statusbar
set laststatus=2
set ruler
