#!/usr/bin/env bash

# Import functions
source "${HOME}/.dotfiles/share/bash/functions.sh"

# Use dircolors configuration, if available
[ -r "${HOME}/.dir_colors" ] && eval "$(dircolors -b ~/.dir_colors)"

# Source fzf key-bindings/completion
if [ -n "$(command -v fzf)" ]
then
  source_file "/usr/share/bash-completion/completions/fzf"
  source_file "/usr/share/bash-completion/completions/fzf-key-bindings"
  source_file "/usr/share/fzf/shell/key-bindings.bash"
fi
