#!/bin/bash

# Default terminal for i3
if [ "${XDG_CURRENT_DESKTOP}" = "i3" ] && [ "${XDG_SESSION_DESKTOP}" = "i3" ]
then
  export TERMINAL="kitty"
fi

# Remap Caps Lock to Control, use Right Alt as the compose key
setxkbmap \
  -model pc105 \
  -layout "us,br" \
  -option -option "ctrl:nocaps,compose:ralt,grp:alt_space_toggle"

source "${HOME}/.dotfiles/share/bin/system_theme"
