#!/bin/bash

# Default terminal for i3
if [ "${XDG_CURRENT_DESKTOP}" = "i3" ] && [ "${XDG_SESSION_DESKTOP}" = "i3" ]
then
  export TERMINAL="kitty"
fi

# Remap Caps Lock to Control, use Right Alt as the compose key
setxkbmap \
  -model pc105 \
  -layout "us,br" \
  -option -option "ctrl:nocaps,compose:ralt,grp:alt_space_toggle"

# vim/emacs/tmux/kitty color themes depending on time
# Light theme from 07h00 to 20h00, dark theme otherwise

CURRENT_TIME="$(date +%k%H)"

if [ "${CURRENT_TIME}" -ge 700 ] && [ "${CURRENT_TIME}" -lt 2000 ]
then
  export SYSTEM_THEME="seoul256_light"
else
  export SYSTEM_THEME="challenger_deep"
fi
