#!/usr/bin/env bash

# Import functions
source "${HOME}/.dotfiles/bash/functions.sh"

# Source global definitions
source_file /etc/bashrc

# Get bash aliases from file if there is one
source_file "${HOME}/.bash_aliases"

# Source machine-specific configuration
source_file "${HOME}/.bashrc.local"

# Source OS-specific configuration
source_file "${HOME}/.bashrc_os"

# Source fzf key-bindings/completion
source_file "/usr/share/fzf/shell/key-bindings.bash"
source_file "/usr/share/bash-completion/completions/fzf"

# Define vim/vi as the default editor, if available
if [ -n "$(command -v vimx)" ]
then
  export EDITOR=vimx
elif [ -n "$(command -v vim)" ]
then
  export EDITOR=vim
elif [ -n "$(command -v vi)" ]
then
  export EDITOR=vi
fi

source_file "${HOME}/.dotfiles/bash/prompt.sh"
