#!/bin/bash

# bash script for aliases

# Alias for vimx (on Fedora)
if [[ -e /usr/bin/vimx ]]; then alias vim="/usr/bin/vimx"; fi

# tmux minimal session for workspace
if [[ -n "$(command -v tmux)" && -d ${HOME}/workspace ]]; then
  alias workspace="tmux new-session -s workspace -n home -c $HOME/workspace"
fi

# tmux rename window based on current working directory
_rename_tmux_window() {
  if [[ -n $TMUX ]]; then
    if [[ -n "$(git_base_directory)" ]]; then
      tmux rename-window $(git_base_directory)
    else
      tmux rename-window $(basename $PWD)
    fi
  fi
}

alias tname='_rename_tmux_window'

# Alias for listing local branches which no longer have their remote counterpart
alias ggone="git branch -vv | grep -i '\[.* gone\]' | awk '{ print \$1 }'"

_filter_git_modified_untracked_files() {
  local filter=$1

  git status -su \
    | grep -E "^(\?\?|[MR ]M| D)" \
    | awk '{ print $2 }' \
    | grep -iE "${filter}"
}

# Alias for filtering modified/untracked git files in a branch
alias gmu="_filter_git_modified_untracked_files"

# Local aliases

if [ -f ~/.bash_aliases.local ]; then source ~/.bash_aliases.local; fi
