#!/bin/bash

# bash script for aliases

if [[ -e /usr/bin/vimx ]]; then alias vim="/usr/bin/vimx"; fi

# tmux minimal session for workspace
if [[ -n "$(command -v tmux)" && -d ${HOME}/workspace ]]; then
  alias workspace="tmux new-session -s main -n workspace -c $HOME/workspace"
fi

# Local aliases

if [ -f ~/.bash_aliases.local ]; then source ~/.bash_aliases.local; fi
